### ISSUE TITLE
Add code to big business filter to remove all listings with the same address

### ISSUE THREAD

**Issue by ethanimooney** [googleinterns/SmallCity#34]
For example, I had a walgreens that shows as walgreens, redbox, and 2 pharmacists. So we need to add code to make sure to remove everything with the exact same address as a big business

**Comment by ethanimooney** [comment]
Is this being worked on @AbakirH ?

**Comment by AbakirH** [comment]
With the checks, I have this is resolved on its own. Each business is still being pushed into the database, with different names. Also, you can not forget sometimes business all reside in the same address, so that could be a problem if I make a check based on the address some small business, might get removed.

**Comment by ethanimooney** [comment]
Being worked on

**Comment by LindseyWeiskopf** [comment]
Decided that this was not needed because all of the big businesses are being added and businesses may share the same address.
